version: '3.8'

services:
  backend:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/commit-to-kids-backend:${IMAGE_TAG:-latest}
    container_name: commit-to-kids-backend
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=${DATABASE_URL:-sqlite:////app/data/webui.db}
      - WEBUI_AUTH=true
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-86400}
      - ENABLE_SIGNUP=${ENABLE_SIGNUP:-false}
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
    volumes:
      - backend-data:/app/data
    networks:
      - app-network
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    logging:
      driver: awslogs
      options:
        awslogs-group: /ecs/commit-to-kids
        awslogs-region: ${AWS_REGION}
        awslogs-stream-prefix: backend

  frontend:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/commit-to-kids-frontend:${IMAGE_TAG:-latest}
    container_name: commit-to-kids-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://backend:8080}
      - NEXT_PUBLIC_WS_URL=${NEXT_PUBLIC_WS_URL:-ws://backend:8080}
      - NEXT_PUBLIC_ENABLE_SIGNUP=${NEXT_PUBLIC_ENABLE_SIGNUP:-false}
      - NEXT_PUBLIC_APP_NAME=${NEXT_PUBLIC_APP_NAME:-Commit to Kids}
    depends_on:
      - backend
    networks:
      - app-network
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    logging:
      driver: awslogs
      options:
        awslogs-group: /ecs/commit-to-kids
        awslogs-region: ${AWS_REGION}
        awslogs-stream-prefix: frontend

  nginx:
    image: nginx:alpine
    container_name: commit-to-kids-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-network
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    logging:
      driver: awslogs
      options:
        awslogs-group: /ecs/commit-to-kids
        awslogs-region: ${AWS_REGION}
        awslogs-stream-prefix: nginx

volumes:
  backend-data:
    driver: local

networks:
  app-network:
    driver: bridge