version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: commit-to-kids-backend
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=sqlite:////app/data/webui.db
      - WEBUI_AUTH=true
      - JWT_EXPIRES_IN=86400
      - ENABLE_SIGNUP=true
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY:-your-secret-key-here}
    volumes:
      - backend-data:/app/data
      - ./backend:/app:delegated
    command: python main.py
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: commit-to-kids-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8080
      - NEXT_PUBLIC_WS_URL=ws://backend:8080
      - NEXT_PUBLIC_ENABLE_SIGNUP=true
      - NEXT_PUBLIC_APP_NAME=Commit to Kids
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: commit-to-kids-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-network
    restart: unless-stopped

volumes:
  backend-data:
    driver: local

networks:
  app-network:
    driver: bridge